//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpAssginment.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public int City { get; set; }
        public string Country { get; set; }
        public string Post_Code { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public bool Active { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual City City1 { get; set; }
    }
}
